openapi: 3.0.3
info:
  title: Brand Coordinator
  description: Swagger
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: summary
    description: everything about price summary
  - name: product
    description: everything about product
  - name: brand
    description: everything about brand
paths:
  '/api/v1/get-summary-by-category':
    get:
      tags:
        - summary
      summary: Get summary by category
      description: Get summary by category
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryBrandProductSummaryResponse'
  '/api/v1/get-summary-each-category':
    get:
      tags:
        - summary
      summary: Get summary each category
      description: Get summary each category
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandProductSummaryResponse'
  '/api/v1/get-summary-lowest-brand':
    get:
      tags:
        - summary
      summary: Get summary lowest brand
      description: Get summary lowest brand
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LowestBrandProductSummaryResponse'
  '/api/v1/products':
    get:
      tags:
        - product
      summary: Find all products
      description: Find all products
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Invalid request
    post:
      tags:
        - product
      summary: Add product
      description: Add product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductPostRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
              example:
                ValidationError:
                  summary: Validation error
                  value:
                    category: 'category is required'
                    brandName: 'brandName is required'
                    price: 'price must be positive or zero'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponse'
              example:
                NotFoundException:
                  summary: Product not found by name
                  value:
                    message: '상의 Product is not found by name'
  '/api/v1/products/{id}':
    patch:
      tags:
        - product
      summary: Update product
      description: Update product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductPatchRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
              example:
                ValidationError:
                  summary: Validation error
                  value:
                    price: 'price must be positive or zero'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponse'
              example:
                NotFoundException:
                  summary: Product not found by id
                  value:
                    message: '1 Product is not found by id'
    delete:
      tags:
        - product
      summary: Delete product
      description: Delete product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponse'
              example:
                NotFoundException:
                  summary: Product not found by id
                  value:
                    message: '1 Product is not found by id'
  '/api/v1/brands':
    get:
      tags:
        - brand
      summary: Find all brands
      description: Find all brands
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
    post:
      tags:
        - brand
      summary: Add brand
      description: Add brand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandPostRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/CommonErrorResponse'
              examples:
                ValidationError:
                  summary: Validation error
                  value:
                    name: 'name is required'
                AlreadyExistBrandException:
                  summary: Already exist brand exception
                  value:
                    message: 'Brand with name A already exists'
  '/api/v1/brands/{id}':
    patch:
      tags:
        - brand
      summary: Update brand
      description: Update brand
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandPatchRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brand'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/CommonErrorResponse'
              examples:
                ValidationError:
                  summary: Validation error
                  value:
                    name: 'name is required'
                AlreadyExistBrandException:
                  summary: Already exist brand exception
                  value:
                    message: 'Brand with name A already exists'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponse'
              example:
                NotFoundException:
                  summary: Product not found by name
                  value:
                    message: '1 Brand is not found by id'
    delete:
      tags:
        - brand
      summary: Delete brand
      description: Delete brand
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/CommonErrorResponse'
              example:
                ValidationError:
                  summary: Validation error
                  value:
                    price: 'price must be positive or zero'
                BrandInUseByProductException:
                  summary: Brand is used by product
                  value:
                    message: '1 Brand is used by product'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonErrorResponse'
              example:
                NotFoundException:
                  summary: Product not found by name
                  value:
                    message: '1 Brand is not found by id'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        category:
          type: string
          example: 상의
        brand_name:
          type: string
          example: A
        price:
          type: integer
          example: 10000
    ProductPostRequest:
      type: object
      required:
        - category
        - brand_name
        - price
      properties:
        category:
          type: string
          example: 정장
        brand_name:
          type: string
          example: A
        price:
          type: integer
          example: 200000
    ProductPatchRequest:
      type: object
      properties:
        category:
          type: string
          example: 정장
        brand_name:
          type: string
          example: A
        price:
          type: integer
          example: 300000
    Brand:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: A
    BrandPostRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: A
    BrandPatchRequest:
      type: object
      properties:
        name:
          type: string
          example: B
    CategoryBrandProductSummaryResponse:
      type: object
      required:
        - category
        - minimum
        - maximum
      properties:
        category:
          type: string
          example: 상의
        minimum:
          type: array
          items:
            $ref: '#/components/schemas/BrandProduct'
          example:
            - {brand_name: C, price: 1000}
        maximum:
          type: array
          items:
            $ref: '#/components/schemas/BrandProduct'
          example:
            - {brand_name: I, price: 11400}
    BrandProductSummaryResponse:
      type: object
      required:
        - amount
        - products
      properties:
        amount:
          type: integer
          example: 34100
        products:
          type: array
          items:
            $ref: '#/components/schemas/BrandProduct'
          example:
            - {category: 스니커즈, brand_name: G, price: 9000}
            - {category: 아우터, brand_name: E, price: 5000}
            - {category: 바지, brand_name: D, price: 3000}
            - {category: 스니커즈, brand_name: G, price: 9000}
            - {category: 가방, brand_name: A, price: 2000}
            - {category: 모자, brand_name: D, price: 1500}
            - {category: 양말, brand_name: I, price: 1700}
            - {category: 액세서리, brand_name: F, price: 1900}
    LowestBrandProductSummaryResponse:
      type: object
      required:
        - brand_name
        - products
        - amount
      properties:
        brand_name:
          type: string
          example: D
        products:
          type: array
          items:
            $ref: '#/components/schemas/BrandProduct'
          example:
            - { category: 상의, price: 10100 }
            - { category: 아우터, price: 5100 }
            - { category: 바지, price: 3000 }
            - { category: 스니커즈, price: 9500 }
            - { category: 가방, price: 2500 }
            - { category: 모자, price: 1500 }
            - { category: 양말, price: 2400 }
            - { category: 액세서리, price: 2000 }
        amount:
          type: integer
          example: 36100
    BrandProduct:
      type: object
      required:
        - price
      properties:
        category:
          type: string
          example: 상의
        brand_name:
          type: string
          example: A
        price:
          type: integer
          example: 11200
    CommonErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: A Brand is used by product
    ValidationErrorResponse:
      type: object
      additionalProperties:
        type: string
      example:
        category: 'category is required'
        brandName: 'brandName is required'
        price: 'price must be positive or zero'
